### ISSUE TITLE
twisted.protocols.telnet got deprecated.

### ISSUE THREAD

**Issue by vloup** [foospidy/HoneyPy#34]
Since Twisted version 17.1.0 released in February 2017, twisted.protocols.telnet got removed in favor of twisted.conch.telnet.

So now, upon trying to launch HoneyPy with a bigger version of Twisted, we are welcomed with:
```
Traceback (most recent call last):
  File "Honey.py", line 121, in <module>
    plugin = importlib.import_module(plugin_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/share/honeypy-git/plugins/TelnetUnix/__init__.py", line 5, in <module>
    from TelnetUnix import pluginFactory
  File "/usr/share/honeypy-git/plugins/TelnetUnix/TelnetUnix.py", line 10, in <module>
    from twisted.protocols.telnet import *
ImportError: No module named telnet
```

**Comment by foospidy** [comment]
Hi, sorry for the delayed response.

In the requirements file it specifies installing 14.0.2
https://github.com/foospidy/HoneyPy/blob/master/requirements.txt#L3

That version will need to be used to avoid the issue you're running into. If you need version 17 for other apps, then I recommend running HoneyPy in a virtualenv with 14.0.2 installed.
